name: Bug Report
description: Report a bug, crash, or unexpected behavior to help us fix broken stuff.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        Please make sure there isn't another issue reporting the same problem as
        yours, thanks!
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: >-
        Please describe in detail the issue you are experiencing and the steps
        on how to reproduce it.
      placeholder: >-
        Every time I do this, the app crashes. To cause this bug, I simply
        clicked a button...
    validations:
      required: true
