name: Segnalazione Bug
title: Segnalazione Bug
description: Segnala un bug in Spotifinity
labels:
  - bug
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: Descrizione bug
      description: Descrivi il bug e come riprodurlo.
    validations:
      required: true
  - type: dropdown
    id: dropdown-1
    attributes:
      label: Piattaforma
      description: In che piattaforma si trova questo bug?
    validations:
      required: true
      options:
        - Android
        - Windows
  - type: input
    id: input-2
    attributes:
      label: Versione App
      description: Qual'è la versione di Spotifinity che stai usando?
      placeholder: v10
    validations:
      required: true
  - type: input
    id: input-3
    attributes:
      label: Versione OS
      description: Qual'è la versione del tuo sistema operativo?
      placeholder: "14"
